title: 'COMSOL Server'
connection: 'connection.html.mustache'
compute:
  - name: 'COMSOL Server'
    batch: 'oakley'
    node:
      - type: 'any'
        ppn: 12
        desc: >
          Choose any type of compute node. This reduces the wait time
          as there are no node specific requirements.
    webserver?: true
    pbs:
      envvars:
        COMSOL_MODULE: 'comsol/52au3_server'
        COMSOL_APP_TOKEN: 'comsol_server'
